server:
  port: 8887
spring:
  application:
    name: consumerwithnativeconfig
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true