server:
  port: 8866
spring:
  application:
    name: github_configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/taroballscai/springcloud.git
          search-paths: config
          username: taroballscai
          password: jsjxh123
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka